descriptor-schema-version: "2.2"

info:
  name: JEA-FogLAMP-Docker-IOx
  description: "IOx FogLAMP DNP3 Dev image with utils"
  version: "2.1.0"
  author-link: "https://raesemann.com"
  author-name: "Rob Raesemann"
app:
  cpuarch: "x86_64"
  type: docker
  env:
    FOGLAMP_ROOT: /usr/local/foglamp
  resources:
    profile: custom
    cpu: "7000"
    disk: "51200"
    memory: "2048"
    network:
      -
        interface-name: eth1
        ports:
          tcp: [8081, 8080, 4840, 1995, 502, 23]
  startup:
    rootfs: rootfs.tar
    target: ["bash", "/usr/local/foglamp/foglamp.sh"]